### PR TITLE
Update sign in form

### PR DESCRIPTION
**Pull request by gerardogalvez**
Added <br> tags between fields for better viewing.

### CODE REVIEW

**Comment by andrewhavens** [comment]
Thank you! I didn't notice this until you mentioned it. Actually, the thing that is missing is that the `<form>` tag should have `class="form-horizontal"`. Do you mind changing this instead of using `<br>` tags?

**Comment by gerardogalvez** [comment]
So instead o <div class="form-group"> it should be <div class="form-horizontal">?

**Comment by andrewhavens** [comment]
Oops. This line: https://github.com/ruby-rcade/RubyGameDev.com/pull/36/files#diff-2925e953161860b4fe184dbbda35cee9R1

It should look like this:

    <%= form_for :session, :url => session_path, html: { class: 'form-horizontal' } do |form| %>

I forget that `class` is within `html`

**Comment by gerardogalvez** [comment]
Hi. It´s done!

**Comment by andrewhavens** [comment]
Looks good! Thank you!

**Pull request merged**
